// @ts-check
/**
 * 把项目规范里能静态检查的条款变成测试。
 *
 * 这些是回归守卫：以后谁把 `Date.now()` 写回领域层、或在代码注释里塞 emoji，
 * 测试会当场拦下来，而不是等到线上才发现。
 */
import assert from 'node:assert/strict'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { test } from 'node:test'

const packageRoot = new URL('..', import.meta.url)

/** Every .js file below `dirUrl` (missing directories are simply empty). */
function jsFiles(dirUrl) {
  if (!existsSync(dirUrl)) return []
  const out = []
  for (const entry of readdirSync(dirUrl, { withFileTypes: true })) {
    const child = new URL(`${entry.name}${entry.isDirectory() ? '/' : ''}`, dirUrl)
    if (entry.isDirectory()) out.push(...jsFiles(child))
    else if (entry.name.endsWith('.js')) out.push(child)
  }
  return out
}

const read = url => readFileSync(url, 'utf8')
const shortName = url => url.pathname.split('/').slice(-2).join('/')

test('the domain layer never reads the system clock', () => {
  // core.js is the barrel; core/ holds the modules it re-exports.
  const files = [new URL('core.js', packageRoot), ...jsFiles(new URL('core/', packageRoot))]
  const offenders = files.filter(url => /Date\.now\(\)/.test(read(url))).map(shortName)
  assert.deepEqual(
    offenders,
    [],
    'pass nowMs in as a parameter instead of reading the clock inside core (CONVENTIONS §分层)',
  )
})

test('code identifiers, comments and logs carry no emoji', () => {
  // Game data (data/) and user-facing copy (CHANGELOG, panel strings) are exempt
  // by the project conventions; this checks the code layers.
  const emoji = /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE0F}]/u
  const files = [
    new URL('core.js', packageRoot),
    new URL('index.js', packageRoot),
    new URL('store.js', packageRoot),
    new URL('render.js', packageRoot),
    ...jsFiles(new URL('core/', packageRoot)),
    ...jsFiles(new URL('store/', packageRoot)),
    // TODO(2026-09-30): src/client/index.js is still one file (2192 lines).
    // It joins this list when stage 2 of docs/REFACTOR-PLAN.md splits it; until
    // then the bundle is generated from it and must stay a single source file.
  ]
  const offenders = []
  for (const url of files) {
    read(url).split('\n').forEach((line, index) => {
      const stripped = line.trim()
      const isComment = stripped.startsWith('//') || stripped.startsWith('/*') || stripped.startsWith('*')
      if (isComment && emoji.test(line)) offenders.push(`${shortName(url)}:${index + 1}`)
    })
  }
  assert.deepEqual(offenders, [], 'comments explain why in words; emoji belong in the game data and UI copy')
})

test('source files stay under the 400-line ceiling', () => {
  // client.js is generated by scripts/build-client.mjs, so it is exempt.
  const files = [
    new URL('index.js', packageRoot),
    new URL('snapshot.js', packageRoot),
    new URL('commands.js', packageRoot),
    new URL('routes.js', packageRoot),
    new URL('store.js', packageRoot),
    new URL('render.js', packageRoot),
    ...jsFiles(new URL('data/', packageRoot)),
    ...jsFiles(new URL('core/', packageRoot)),
    ...jsFiles(new URL('store/', packageRoot)),
    // TODO(2026-09-30): src/client/index.js is still one file (2192 lines).
    // It joins this list when stage 2 of docs/REFACTOR-PLAN.md splits it; until
    // then the bundle is generated from it and must stay a single source file.
  ]
  const lineCount = url => read(url).replace(/\n$/, '').split('\n').length
  const offenders = files.filter(url => lineCount(url) > 400).map(url => `${shortName(url)}:${lineCount(url)}`)
  assert.deepEqual(offenders, [], 'split the file instead of growing past 400 lines (CONVENTIONS §分层)')
})

test('package.json ships every module the runtime imports', () => {
  // Splitting files is only safe if the published tarball carries them: the
  // `files` allow-list decides that, and a missing directory breaks the plugin
  // for anyone who installs it from npm (the local link hides the mistake).
  const manifest = JSON.parse(read(new URL('package.json', packageRoot)))
  const listed = new Set(manifest.files)
  const required = [
    'index.js', 'snapshot.js', 'commands.js', 'routes.js', 'core.js', 'data.js',
    'store.js', 'render.js', 'client.js', 'core', 'data', 'store', 'src', 'scripts',
  ]
  const missing = required.filter(entry => !listed.has(entry))
  assert.deepEqual(missing, [], 'add these to package.json files:')
  const absent = [...listed].filter(entry => !existsSync(new URL(entry, packageRoot)))
  assert.deepEqual(absent, [], 'files lists something that is not in the package:')
})
