// @ts-check
/** C4 图鉴：小闪卡、动森式博物馆格与紧凑道具目录。 */

export const CSS_DEX = [
  // Category dashboard: existing app tiles plus a thin museum-style progress rail.
  '.dp-dex-sections .dp-tile{gap:3px}',
  '.dp-dex-progress{display:block;width:42px;height:3px;margin-top:1px;border-radius:4px;overflow:hidden;',
  'background:rgba(61,52,40,.12)}',
  '.dp-dex-progress i{display:block;height:100%;border-radius:inherit;background:var(--tile-c,var(--ac-primary));',
  'transition:width .25s var(--ac-ease)}',

  // Forms and skins: three genuinely small collectible cards.
  '.dp-dex-flash-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;perspective:700px}',
  '.dp-dex-card{position:relative;min-width:0;aspect-ratio:4/5;padding:4px;border:1.5px solid rgba(117,91,48,.3);',
  'border-radius:11px;overflow:hidden;cursor:pointer;color:var(--ac-text);font:inherit;',
  'background:linear-gradient(145deg,#fff9dc 0%,#f5dd9e 38%,#e8bfcf 68%,#b9ddec 100%);',
  'box-shadow:0 3px 0 rgba(61,52,40,.13),0 6px 12px rgba(91,67,37,.09);',
  'transform:rotateX(var(--dex-rx,0deg)) rotateY(var(--dex-ry,0deg));transform-style:preserve-3d;',
  'transition:transform .18s var(--ac-ease),box-shadow .18s var(--ac-ease)}',
  '.dp-dex-card:hover{transform:translateY(-2px) rotateX(var(--dex-rx,-2deg)) rotateY(var(--dex-ry,3deg));',
  'box-shadow:0 5px 0 rgba(61,52,40,.11),0 9px 16px rgba(91,67,37,.14)}',
  '.dp-dex-card:focus-visible,.dp-dex-museum-item:focus-visible,.dp-dex-row:focus-visible{outline:2px solid var(--ac-primary);outline-offset:2px}',
  '.dp-dex-card-foil::after,.dp-dex-big-foil::after{content:"";position:absolute;inset:-45%;pointer-events:none;',
  'background:linear-gradient(112deg,transparent 32%,rgba(255,255,255,.08) 42%,rgba(255,255,255,.7) 49%,',
  'rgba(155,224,255,.3) 54%,transparent 66%);transform:translateX(-58%) rotate(5deg);',
  'transition:transform .65s ease;mix-blend-mode:screen}',
  '.dp-dex-card-foil:hover::after,.dp-dex-big-foil:hover::after{transform:translateX(58%) rotate(5deg)}',
  '.dp-dex-card-locked{background:linear-gradient(145deg,#e4e2dc,#bbbcb9 52%,#d4d0ca);border-color:#aaa7a0}',
  '.dp-dex-artbox{position:relative;height:calc(100% - 19px);display:flex;align-items:center;justify-content:center;',
  'border-radius:8px;background:rgba(255,255,255,.55);box-shadow:inset 0 0 0 1px rgba(255,255,255,.7);overflow:hidden}',
  '.dp-dex-art{display:block;width:88%;height:88%;object-fit:contain;filter:drop-shadow(0 3px 2px rgba(61,52,40,.16));',
  'transform:translateZ(10px);transition:transform .18s var(--ac-ease)}',
  '.dp-dex-card-foil:hover .dp-dex-art{transform:translateZ(13px) scale(1.04)}',
  '.dp-dex-card-locked .dp-dex-art,.dp-dex-big-locked .dp-dex-art,.dp-dex-museum-locked .dp-dex-art,',
  '.dp-dex-info-locked .dp-dex-art{filter:grayscale(1) brightness(0);opacity:.3}',
  '.dp-dex-emoji{font-size:27px;line-height:1;filter:drop-shadow(0 2px 1px rgba(61,52,40,.14))}',
  '.dp-dex-emoji-large{font-size:42px}',
  '.dp-dex-lock{position:absolute;z-index:2;left:50%;top:50%;transform:translate(-50%,-50%);display:flex;',
  'align-items:center;justify-content:center;width:25px;height:25px;border-radius:50%;font-size:12px;',
  'background:rgba(58,57,54,.78);border:1.5px solid rgba(255,255,255,.82);box-shadow:0 2px 6px rgba(0,0,0,.16)}',
  '.dp-dex-caption{position:relative;z-index:1;display:block;margin-top:4px;font-size:8.5px;font-weight:800;',
  'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:center}',
  '.dp-dex-card-locked .dp-dex-caption{color:#615f5b;letter-spacing:.04em}',

  // Fish and souvenirs: pastel three-column museum shelf, no foil or 3D.
  '.dp-dex-museum{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px 8px}',
  '.dp-dex-museum-item{font:inherit;min-width:0;height:82px;padding:5px;border:0;border-radius:13px;cursor:pointer;',
  'display:flex;flex-direction:column;align-items:center;justify-content:space-between;color:var(--ac-text);',
  'background:var(--ac-bg-content);box-shadow:inset 0 0 0 1.5px var(--ac-border-light)}',
  '.dp-dex-museum-item:nth-child(4n+1){background:#e5f3f5}.dp-dex-museum-item:nth-child(4n+2){background:#f5e6ef}',
  '.dp-dex-museum-item:nth-child(4n+3){background:#eef3df}.dp-dex-museum-item:nth-child(4n){background:#f8efd9}',
  '.dp-dex-museum-art{position:relative;display:flex;align-items:center;justify-content:center;width:100%;height:54px}',
  '.dp-dex-museum-art .dp-dex-art{width:48px;height:48px}',
  '.dp-dex-museum-lock{position:absolute;right:1px;top:1px;font-size:10px}',
  '.dp-dex-museum-name{display:block;width:100%;font-size:8.5px;font-weight:800;white-space:nowrap;',
  'overflow:hidden;text-overflow:ellipsis;text-align:center}',
  '.dp-dex-museum-locked{filter:grayscale(.45);color:var(--ac-text-2)}',

  // Item catalogue: search + wraparound category chips + dense rows.
  '.dp-dex-catalog-tools{margin-bottom:8px}',
  '.dp-dex-search{width:100%;height:28px;margin:0 0 6px;padding:4px 10px;font-size:10px}',
  '.dp-dex-filters{display:flex;gap:4px;overflow-x:auto;padding:1px 0 3px;scrollbar-width:none}',
  '.dp-dex-filters::-webkit-scrollbar{display:none}',
  '.dp-dex-filter{font:inherit;flex:none;border:1.5px solid var(--ac-border-light);border-radius:var(--ac-pill);',
  'background:var(--ac-bg-input);color:var(--ac-text-2);padding:3px 8px;font-size:9px;font-weight:700;cursor:pointer}',
  '.dp-dex-filter[data-active="true"]{background:var(--tile-orange);border-color:#cc7950;color:#fff}',
  '.dp-dex-catalog{display:flex;flex-direction:column;gap:5px}',
  '.dp-dex-row{font:inherit;width:100%;min-width:0;border:1.5px solid var(--ac-border-light);border-radius:10px;',
  'background:var(--ac-bg-content);color:var(--ac-text);padding:5px 8px;display:flex;align-items:center;gap:8px;cursor:pointer;text-align:left}',
  '.dp-dex-row-emoji{flex:none;width:25px;text-align:center;font-size:19px}',
  '.dp-dex-row-text{flex:1;min-width:0;display:flex;flex-direction:column}',
  '.dp-dex-row-text b{font-size:10.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.dp-dex-row-text small{font-size:8.5px;color:var(--ac-text-2)}',
  '.dp-dex-row-count{flex:none;font-size:9px;font-weight:800;color:var(--ac-text-2)}',
  '.dp-dex-row-locked{color:var(--ac-text-2);background:#efeee9}',
  '.dp-dex-row[data-search-hidden="true"]{display:none}',

  // A detail replaces the shelf instead of stretching it underneath.
  '.dp-dex-detail{perspective:800px}',
  '.dp-dex-big,.dp-dex-info{position:relative;overflow:hidden;padding:12px;border-radius:18px;',
  'border:2px solid rgba(177,127,43,.4);background:linear-gradient(145deg,#fff8cf 0%,#f6d48c 32%,#efb8d1 61%,#a9d9ec 100%);',
  'box-shadow:0 4px 0 rgba(61,52,40,.13),0 10px 22px rgba(91,67,37,.12)}',
  '.dp-dex-big{transform-style:preserve-3d;transform:rotateX(var(--dex-rx,0deg)) rotateY(var(--dex-ry,0deg));transition:transform .18s ease}',
  '.dp-dex-big-locked{background:linear-gradient(145deg,#e9e7e1,#c5c5c1 56%,#ddd9d3);border-color:#aaa7a0}',
  '.dp-dex-info{background:#fffaf0;border-color:var(--ac-border-light)}',
  '.dp-dex-info-locked{background:#e9e7e1;border-color:#aaa7a0}',
  '.dp-dex-big-art,.dp-dex-info-art{position:relative;height:112px;display:flex;align-items:center;justify-content:center;',
  'border-radius:14px;background:rgba(255,255,255,.5);box-shadow:inset 0 0 0 1px rgba(255,255,255,.76);overflow:hidden}',
  '.dp-dex-info-art{height:92px}.dp-dex-big-art .dp-dex-art{width:106px;height:106px}',
  '.dp-dex-info-art .dp-dex-art{width:82px;height:82px}',
  '.dp-dex-big-title{position:relative;z-index:1;margin-top:9px;font-size:14px;font-weight:900;text-align:center;color:var(--ac-text)}',
  '.dp-dex-riddle{position:relative;z-index:1;margin-top:8px;padding:8px 10px;border-radius:12px;background:rgba(255,255,255,.55);',
  'font-size:10.5px;font-weight:600;line-height:1.55;color:var(--ac-text-body)}',
  '.dp-dex-riddle b{display:block;margin-bottom:2px;font-size:9px;letter-spacing:.14em;color:#766f65}',
  '.dp-dex-story{position:relative;z-index:1;margin-top:7px;font-size:10.5px;font-weight:600;line-height:1.5;',
  'text-align:center;color:var(--ac-text-body)}',
  '.dp-dex-foot{position:relative;z-index:1;margin-top:8px;padding-top:7px;border-top:1px dashed rgba(87,69,42,.3);',
  'font-size:9.5px;font-weight:700;text-align:center;color:var(--ac-text-2)}',
  '.dp-dex-skin-action{position:relative;z-index:1;display:flex;margin-top:16px;justify-content:center}',
  '@media (prefers-reduced-motion:reduce){.dp-dex-card,.dp-dex-big,.dp-dex-art{transition:none!important;transform:none!important}',
  '.dp-dex-card-foil::after,.dp-dex-big-foil::after{display:none}}',
].join('')
